/*
 * Copyright (c) 2014, Inferno Embedded
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the Make, Hack, Void nor the
 *    names of its contributors may be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL MAKE, HACK, VOID BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef FLAME_IO_ARDUINO_MEGA_H_
#define FLAME_IO_ARDUINO_MEGA_H_

#define FLAME_ARDUINO_PIN_0	FLAME_PIN_E0
#define FLAME_ARDUINO_PIN_1	FLAME_PIN_E1
#define FLAME_ARDUINO_PIN_2	FLAME_PIN_E4
#define FLAME_ARDUINO_PIN_3	FLAME_PIN_E5
#define FLAME_ARDUINO_PIN_4	FLAME_PIN_G5
#define FLAME_ARDUINO_PIN_5	FLAME_PIN_E3
#define FLAME_ARDUINO_PIN_6	FLAME_PIN_H3
#define FLAME_ARDUINO_PIN_7	FLAME_PIN_H4
#define FLAME_ARDUINO_PIN_8	FLAME_PIN_H5
#define FLAME_ARDUINO_PIN_9	FLAME_PIN_H6
#define FLAME_ARDUINO_PIN_10	FLAME_PIN_B4
#define FLAME_ARDUINO_PIN_11	FLAME_PIN_B5
#define FLAME_ARDUINO_PIN_12	FLAME_PIN_B6
#define FLAME_ARDUINO_PIN_13	FLAME_PIN_B7
#define FLAME_ARDUINO_PIN_14	FLAME_PIN_J1
#define FLAME_ARDUINO_PIN_15	FLAME_PIN_J0
#define FLAME_ARDUINO_PIN_16	FLAME_PIN_H1
#define FLAME_ARDUINO_PIN_17	FLAME_PIN_H0
#define FLAME_ARDUINO_PIN_18	FLAME_PIN_D3
#define FLAME_ARDUINO_PIN_19	FLAME_PIN_D2
#define FLAME_ARDUINO_PIN_20	FLAME_PIN_D1
#define FLAME_ARDUINO_PIN_21	FLAME_PIN_D0
#define FLAME_ARDUINO_PIN_22	FLAME_PIN_A0
#define FLAME_ARDUINO_PIN_23	FLAME_PIN_A1
#define FLAME_ARDUINO_PIN_24	FLAME_PIN_A2
#define FLAME_ARDUINO_PIN_25	FLAME_PIN_A3
#define FLAME_ARDUINO_PIN_26	FLAME_PIN_A4
#define FLAME_ARDUINO_PIN_27	FLAME_PIN_A5
#define FLAME_ARDUINO_PIN_28	FLAME_PIN_A6
#define FLAME_ARDUINO_PIN_29	FLAME_PIN_A7
#define FLAME_ARDUINO_PIN_30	FLAME_PIN_C7
#define FLAME_ARDUINO_PIN_31	FLAME_PIN_C6
#define FLAME_ARDUINO_PIN_32	FLAME_PIN_C5
#define FLAME_ARDUINO_PIN_33	FLAME_PIN_C4
#define FLAME_ARDUINO_PIN_34	FLAME_PIN_C3
#define FLAME_ARDUINO_PIN_35	FLAME_PIN_C2
#define FLAME_ARDUINO_PIN_36	FLAME_PIN_C1
#define FLAME_ARDUINO_PIN_37	FLAME_PIN_C0
#define FLAME_ARDUINO_PIN_38	FLAME_PIN_D7
#define FLAME_ARDUINO_PIN_39	FLAME_PIN_G2
#define FLAME_ARDUINO_PIN_40	FLAME_PIN_G1
#define FLAME_ARDUINO_PIN_41	FLAME_PIN_G0
#define FLAME_ARDUINO_PIN_42	FLAME_PIN_L7
#define FLAME_ARDUINO_PIN_43	FLAME_PIN_L6
#define FLAME_ARDUINO_PIN_44	FLAME_PIN_L5
#define FLAME_ARDUINO_PIN_45	FLAME_PIN_L4
#define FLAME_ARDUINO_PIN_46	FLAME_PIN_L3
#define FLAME_ARDUINO_PIN_47	FLAME_PIN_L2
#define FLAME_ARDUINO_PIN_48	FLAME_PIN_L1
#define FLAME_ARDUINO_PIN_49	FLAME_PIN_L0
#define FLAME_ARDUINO_PIN_50	FLAME_PIN_B3
#define FLAME_ARDUINO_PIN_51	FLAME_PIN_B2
#define FLAME_ARDUINO_PIN_52	FLAME_PIN_B1
#define FLAME_ARDUINO_PIN_53	FLAME_PIN_B0
#define FLAME_ARDUINO_PIN_A0	FLAME_PIN_F0
#define FLAME_ARDUINO_PIN_A1	FLAME_PIN_F1
#define FLAME_ARDUINO_PIN_A2	FLAME_PIN_F2
#define FLAME_ARDUINO_PIN_A3	FLAME_PIN_F3
#define FLAME_ARDUINO_PIN_A4	FLAME_PIN_F4
#define FLAME_ARDUINO_PIN_A5	FLAME_PIN_F5
#define FLAME_ARDUINO_PIN_A6	FLAME_PIN_F6
#define FLAME_ARDUINO_PIN_A7	FLAME_PIN_F7
#define FLAME_ARDUINO_PIN_A8	FLAME_PIN_K0
#define FLAME_ARDUINO_PIN_A9	FLAME_PIN_K1
#define FLAME_ARDUINO_PIN_A10	FLAME_PIN_K2
#define FLAME_ARDUINO_PIN_A11	FLAME_PIN_K3
#define FLAME_ARDUINO_PIN_A12	FLAME_PIN_K4
#define FLAME_ARDUINO_PIN_A13	FLAME_PIN_K5
#define FLAME_ARDUINO_PIN_A14	FLAME_PIN_K6
#define FLAME_ARDUINO_PIN_A15	FLAME_PIN_K7

#endif /* FLAME_IO_ARDUINO_MEGA_H_ */
