# Board details can be set here or on the command line as Make arguments
MCU ?= atmega328p
MHZ ?= 16

# PROJECT is the name used for the output files
PROJECT=flame-tutorial-ADC

LIBDIR=../flame
include $(LIBDIR)/project.mk

