/*
 * Copyright (c) 2014, Inferno Embedded
 * All rights reserved.
 *
 *  License: GNU GPL v2 (see flame-Vusb-Keyboard/vusb/License.txt)
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL MAKE, HACK, VOID BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef FLAME_VUSBKEYBOARD_H_
#define FLAME_VUSBKEYBOARD_H_

#include <flame/io.h>
#include <flame/RTC.h>

#define FLAME_MOD_CONTROL_LEFT    (1<<0)
#define FLAME_MOD_SHIFT_LEFT      (1<<1)
#define FLAME_MOD_ALT_LEFT        (1<<2)
#define FLAME_MOD_GUI_LEFT        (1<<3)
#define FLAME_MOD_CONTROL_RIGHT   (1<<4)
#define FLAME_MOD_SHIFT_RIGHT     (1<<5)
#define FLAME_MOD_ALT_RIGHT       (1<<6)
#define FLAME_MOD_GUI_RIGHT       (1<<7)

using namespace flame;
namespace flame_gpl {

enum vusb_keyboard_key {
	FLAME_KEY_A					= 4,
	FLAME_KEY_B					= 5,
	FLAME_KEY_C					= 6,
	FLAME_KEY_D					= 7,
	FLAME_KEY_E					= 8,
	FLAME_KEY_F					= 9,
	FLAME_KEY_G					= 10,
	FLAME_KEY_H					= 11,
	FLAME_KEY_I					= 12,
	FLAME_KEY_J					= 13,
	FLAME_KEY_K					= 14,
	FLAME_KEY_L					= 15,
	FLAME_KEY_M					= 16,
	FLAME_KEY_N					= 17,
	FLAME_KEY_O					= 18,
	FLAME_KEY_P					= 19,
	FLAME_KEY_Q					= 20,
	FLAME_KEY_R					= 21,
	FLAME_KEY_S					= 22,
	FLAME_KEY_T					= 23,
	FLAME_KEY_U					= 24,
	FLAME_KEY_V					= 25,
	FLAME_KEY_W					= 26,
	FLAME_KEY_X					= 27,
	FLAME_KEY_Y					= 28,
	FLAME_KEY_Z					= 29,
	FLAME_KEY_1					= 30,
	FLAME_KEY_2					= 31,
	FLAME_KEY_3					= 32,
	FLAME_KEY_4					= 33,
	FLAME_KEY_5					= 34,
	FLAME_KEY_6					= 35,
	FLAME_KEY_7					= 36,
	FLAME_KEY_8					= 37,
	FLAME_KEY_9					= 38,
	FLAME_KEY_0					= 39,
	FLAME_KEY_ENTER   			= 40,
	FLAME_KEY_ESCAPE				= 41,
	FLAME_KEY_BACKSPACE			= 42,
	FLAME_KEY_TAB				= 43,
	FLAME_KEY_SPACE   			= 44,
	FLAME_KEY_MINUS				= 45,
	FLAME_KEY_EQUALS				= 46,
	FLAME_KEY_L_SQUARE			= 47,
	FLAME_KEY_R_SQUARE			= 48,
	FLAME_KEY_BACKSLASH			= 49,
	FLAME_KEY_NON_US_HASH		= 50,
	FLAME_KEY_SEMICOLON			= 51,
	FLAME_KEY_QUOTE				= 52,
	FLAME_KEY_GRAVE_ACCENT		= 53,
	FLAME_KEY_COMMA				= 54,
	FLAME_KEY_FULLSTOP			= 55,
	FLAME_KEY_SLASH				= 56,
	FLAME_KEY_CAPSLOCK			= 57,
	FLAME_KEY_F1      			= 58,
	FLAME_KEY_F2      			= 59,
	FLAME_KEY_F3      			= 60,
	FLAME_KEY_F4      			= 61,
	FLAME_KEY_F5      			= 62,
	FLAME_KEY_F6      			= 63,
	FLAME_KEY_F7      			= 64,
	FLAME_KEY_F8     			= 65,
	FLAME_KEY_F9      			= 66,
	FLAME_KEY_F10     			= 67,
	FLAME_KEY_F11				= 68,
	FLAME_KEY_F12				= 69,
	FLAME_KEY_PRINTSCREEN		= 70,
	FLAME_KEY_SCROLL_LOCK		= 71,
	FLAME_KEY_PAUSE				= 72,
	FLAME_KEY_INSERT				= 73,
	FLAME_KEY_HOME				= 74,
	FLAME_KEY_PAGE_UP			= 75,
	FLAME_KEY_DELETE				= 76,
	FLAME_KEY_END				= 77,
	FLAME_KEY_PAGE_DOWN			= 78,
	FLAME_KEY_ARROW_RIGHT		= 79,
	FLAME_KEY_ARROW_LEFT			= 80,
	FLAME_KEY_ARROW_DOWN			= 81,
	FLAME_KEY_ARROW_UP			= 82,
	FLAME_KEY_NUM_LOCK			= 83,
	FLAME_KEYPAD_SLASH			= 84,
	FLAME_KEYPAD_ASTERISK		= 85,
	FLAME_KEYPAD_MINUS			= 86,
	FLAME_KEYPAD_PLUS			= 87,
	FLAME_KEYPAD_ENTER			= 88,
	FLAME_KEYPAD_1				= 89,
	FLAME_KEYPAD_2				= 90,
	FLAME_KEYPAD_3				= 91,
	FLAME_KEYPAD_4				= 92,
	FLAME_KEYPAD_5				= 93,
	FLAME_KEYPAD_6				= 94,
	FLAME_KEYPAD_7				= 95,
	FLAME_KEYPAD_8				= 96,
	FLAME_KEYPAD_9				= 97,
	FLAME_KEYPAD_0				= 98,
	FLAME_KEYPAD_FULLSTOP		= 99,
	FLAME_KEY_NON_US_BACKSLASH	= 100,
	FLAME_KEY_APPLICATION		= 101,
	FLAME_KEYPAD_POWER			= 102,
	FLAME_KEYPAD_EQUALS			= 103,
	FLAME_KEY_F13				= 104,
	FLAME_KEY_F14				= 105,
	FLAME_KEY_F15				= 106,
	FLAME_KEY_F16				= 107,
	FLAME_KEY_F17				= 108,
	FLAME_KEY_F18				= 109,
	FLAME_KEY_F19				= 110,
	FLAME_KEY_F20				= 111,
	FLAME_KEY_F21				= 112,
	FLAME_KEY_F22				= 113,
	FLAME_KEY_F23				= 114,
	FLAME_KEY_F24				= 115,
	FLAME_KEY_EXECUTE			= 116,
	FLAME_KEY_HELP				= 117,
	FLAME_KEY_MENU				= 118,
	FLAME_KEY_SELECT				= 119,
	FLAME_KEY_STOP				= 120,
	FLAME_KEY_AGAIN				= 121,
	FLAME_KEY_UNDO				= 122,
	FLAME_KEY_CUT				= 123,
	FLAME_KEY_COPY				= 124,
	FLAME_KEY_PASTE				= 125,
	FLAME_KEY_FIND				= 126,
	FLAME_KEY_MUTE				= 127,
	FLAME_KEY_VOLUME_UP			= 128,
	FLAME_KEY_VOLUME_DOWN		= 129,
	FLAME_KEY_LOCKING_CAPS_LOCK	= 130,
	FLAME_KEY_LOCKING_NUM_LOCK	= 131,
	FLAME_KEY_LOCKING_SCROLL_LOCK = 132,
	FLAME_KEYPAD_COMMA			= 133,
	FLAME_KEYPAD_EQUAL			= 134,
	FLAME_KEY_CONTROL_LEFT		= 224,
	FLAME_KEY_SHIFT_LEFT			= 225,
	FLAME_KEY_ALT_LEFT			= 226,
	FLAME_KEY_GUI_LEFT			= 227,
	FLAME_KEY_CONTROL_RIGHT		= 228,
	FLAME_KEY_SHIFT_RIGHT		= 229,
	FLAME_KEY_ALT_RIGHT			= 230,
	FLAME_KEY_GUI_RIGHT			= 231
};

typedef enum vusb_keyboard_key VUSB_KEYBOARD_KEY;

INLINE VUSB_KEYBOARD_KEY vusb_keyboard_key_add(VUSB_KEYBOARD_KEY key, char c) {
	const uint8_t myKey = key;
	return static_cast<VUSB_KEYBOARD_KEY>(myKey + c);
}

class VusbKeyboard : public TimerListener {
protected:
	RTC		&_rtc;

public:
	VusbKeyboard(RTC &rtc);
	void keyStroke(VUSB_KEYBOARD_KEY key);
	void keyStroke(VUSB_KEYBOARD_KEY key, uint8_t modifiers);
	void keyDown(VUSB_KEYBOARD_KEY key, uint8_t modifiers);
	void keysUp(uint8_t modifiers);
	void keysUp();
	void alarm(AlarmSource source);
};

}
#endif /* FLAME_VUSBKEYBOARD_H_ */
