/*
 * Copyright (c) 2011, Make, Hack, Void Inc
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *  * Neither the name of the Make, Hack, Void nor the
 *    names of its contributors may be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL MAKE, HACK, VOID BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef MHV_IO_ARDUINO_MEGA_H_
#define MHV_IO_ARDUINO_MEGA_H_

#define MHV_ARDUINO_PIN_0	MHV_PIN_E0
#define MHV_ARDUINO_PIN_1	MHV_PIN_E1
#define MHV_ARDUINO_PIN_2	MHV_PIN_E4
#define MHV_ARDUINO_PIN_3	MHV_PIN_E5
#define MHV_ARDUINO_PIN_4	MHV_PIN_G5
#define MHV_ARDUINO_PIN_5	MHV_PIN_E3
#define MHV_ARDUINO_PIN_6	MHV_PIN_H3
#define MHV_ARDUINO_PIN_7	MHV_PIN_H4
#define MHV_ARDUINO_PIN_8	MHV_PIN_H5
#define MHV_ARDUINO_PIN_9	MHV_PIN_H6
#define MHV_ARDUINO_PIN_10	MHV_PIN_B4
#define MHV_ARDUINO_PIN_11	MHV_PIN_B5
#define MHV_ARDUINO_PIN_12	MHV_PIN_B6
#define MHV_ARDUINO_PIN_13	MHV_PIN_B7
#define MHV_ARDUINO_PIN_14	MHV_PIN_J1
#define MHV_ARDUINO_PIN_15	MHV_PIN_J0
#define MHV_ARDUINO_PIN_16	MHV_PIN_H1
#define MHV_ARDUINO_PIN_17	MHV_PIN_H0
#define MHV_ARDUINO_PIN_18	MHV_PIN_D3
#define MHV_ARDUINO_PIN_19	MHV_PIN_D2
#define MHV_ARDUINO_PIN_20	MHV_PIN_D1
#define MHV_ARDUINO_PIN_21	MHV_PIN_D0
#define MHV_ARDUINO_PIN_22	MHV_PIN_A0
#define MHV_ARDUINO_PIN_23	MHV_PIN_A1
#define MHV_ARDUINO_PIN_24	MHV_PIN_A2
#define MHV_ARDUINO_PIN_25	MHV_PIN_A3
#define MHV_ARDUINO_PIN_26	MHV_PIN_A4
#define MHV_ARDUINO_PIN_27	MHV_PIN_A5
#define MHV_ARDUINO_PIN_28	MHV_PIN_A6
#define MHV_ARDUINO_PIN_29	MHV_PIN_A7
#define MHV_ARDUINO_PIN_30	MHV_PIN_C7
#define MHV_ARDUINO_PIN_31	MHV_PIN_C6
#define MHV_ARDUINO_PIN_32	MHV_PIN_C5
#define MHV_ARDUINO_PIN_33	MHV_PIN_C4
#define MHV_ARDUINO_PIN_34	MHV_PIN_C3
#define MHV_ARDUINO_PIN_35	MHV_PIN_C2
#define MHV_ARDUINO_PIN_36	MHV_PIN_C1
#define MHV_ARDUINO_PIN_37	MHV_PIN_C0
#define MHV_ARDUINO_PIN_38	MHV_PIN_D7
#define MHV_ARDUINO_PIN_39	MHV_PIN_G2
#define MHV_ARDUINO_PIN_40	MHV_PIN_G1
#define MHV_ARDUINO_PIN_41	MHV_PIN_G0
#define MHV_ARDUINO_PIN_42	MHV_PIN_L7
#define MHV_ARDUINO_PIN_43	MHV_PIN_L6
#define MHV_ARDUINO_PIN_44	MHV_PIN_L5
#define MHV_ARDUINO_PIN_45	MHV_PIN_L4
#define MHV_ARDUINO_PIN_46	MHV_PIN_L3
#define MHV_ARDUINO_PIN_47	MHV_PIN_L2
#define MHV_ARDUINO_PIN_48	MHV_PIN_L1
#define MHV_ARDUINO_PIN_49	MHV_PIN_L0
#define MHV_ARDUINO_PIN_50	MHV_PIN_B3
#define MHV_ARDUINO_PIN_51	MHV_PIN_B2
#define MHV_ARDUINO_PIN_52	MHV_PIN_B1
#define MHV_ARDUINO_PIN_53	MHV_PIN_B0
#define MHV_ARDUINO_PIN_A0	MHV_PIN_F0
#define MHV_ARDUINO_PIN_A1	MHV_PIN_F1
#define MHV_ARDUINO_PIN_A2	MHV_PIN_F2
#define MHV_ARDUINO_PIN_A3	MHV_PIN_F3
#define MHV_ARDUINO_PIN_A4	MHV_PIN_F4
#define MHV_ARDUINO_PIN_A5	MHV_PIN_F5
#define MHV_ARDUINO_PIN_A6	MHV_PIN_F6
#define MHV_ARDUINO_PIN_A7	MHV_PIN_F7
#define MHV_ARDUINO_PIN_A8	MHV_PIN_K0
#define MHV_ARDUINO_PIN_A9	MHV_PIN_K1
#define MHV_ARDUINO_PIN_A10	MHV_PIN_K2
#define MHV_ARDUINO_PIN_A11	MHV_PIN_K3
#define MHV_ARDUINO_PIN_A12	MHV_PIN_K4
#define MHV_ARDUINO_PIN_A13	MHV_PIN_K5
#define MHV_ARDUINO_PIN_A14	MHV_PIN_K6
#define MHV_ARDUINO_PIN_A15	MHV_PIN_K7

#endif /* MHV_IO_ARDUINO_MEGA_H_ */
